POST http://172.20.0.90:9001/rest/PostCli HTTP/1.1
content-type: application/json

//{"Clientes": [{"A1_COD":"125056","A1_LOJA":"02","A1_NOME":"JACQUELINE KELLY PEREIRA MALARA DE ANDRADE","A1_NREDUZ":"125056-2","A1_TIPO":"F","A1_XPAI":"OSVALDO MALARA DE ANDRADE","A1_XMAE":"SUELI APARECIDA PEREIRA DE ANDRADE","A1_CGC":"29967135832","A1_END":"RUA JOSE RAMON URTIZA","A1_BAIRRO":"VILA ANDRADE","A1_CONTA":"11210002","A1_NUM":"181","A1_EST":"SP","A1_CEP":"05717270","A1_DDD":"11","A1_TEL":"37435679","A1_PFISICA":"22.191.831-0","A1_EMAIL":"jacmalara@hotmail.com","A1_ENDCOB":"RUA QUINZE DE NOVEMBRO,85 CONJ.83","A1_COD_MUN":"50308","A1_XCODOAB":"125056","A1_XDTINSC":"20030829","A1_DTNASC":"19811118","A1_XATINAT":"N","A1_XFLCLIE":"01005701","A1_XADIINA":"A","A1_XTPOAB":"02","A1_PESSOA":"F","A1_BAIRROC":"CENTRO","A1_CEPC":"07011030","A1_MUNC":"GUARULHOS","A1_XPAI2":"OSVALDO","A1_XMAE2":"SUELI","A1_ESTC":"SP","A1_COMPLEM":"APTO 152-A"}]}
//{"Clientes": [{"A1_COD":"234071","A1_LOJA":"01","A1_NOME":"JACQUELINE KELLY PEREIRA MALARA DE ANDRADE","A1_NREDUZ":"234071-1","A1_TIPO":"F","A1_XPAI":"OSVALDO MALARA DE ANDRADE","A1_XMAE":"SUELI APARECIDA PEREIRA DE ANDRADE","A1_CGC":"29967135832","A1_END":"RUA JOSE RAMON URTIZA","A1_BAIRRO":"VILA ANDRADE","A1_CONTA":"11210001","A1_NUM":"181","A1_EST":"SP","A1_CEP":"05717270","A1_DDD":"11","A1_TEL":"37435679","A1_PFISICA":"22.191.831-0","A1_EMAIL":"jacmalara@hotmail.com","A1_ENDCOB":"RUA QUINZE DE NOVEMBRO,85 CONJ.83","A1_COD_MUN":"50308","A1_XCODOAB":"234071","A1_XDTINSC":"20050401","A1_DTNASC":"19811118","A1_XATINAT":"S","A1_XFLCLIE":"01000101","A1_XADIINA":"A","A1_XTPOAB":"01","A1_PESSOA":"F","A1_BAIRROC":"CENTRO","A1_CEPC":"07011030","A1_MUNC":"GUARULHOS","A1_XPAI2":"OSVALDO","A1_XMAE2":"SUELI","A1_ESTC":"SP","A1_COMPLEM":"APTO 152-A"}]}
//{"Clientes": [{"A1_COD":"215851","A1_LOJA":"02","A1_NOME":"DANILO DE SOUZA CUNHA","A1_NREDUZ":"215851-2","A1_TIPO":"F","A1_XPAI":"ALBERTO IRINEU DA CUNHA ","A1_XMAE":"MARIA RAQUEL DE SOUZA CUNHA","A1_CGC":"04662948592","A1_END":"RUA CASTRO ALVES","A1_BAIRRO":"ZONA 06","A1_CONTA":"11210002","A1_NUM":"1390","A1_EST":"PR","A1_CEP":"87015440","A1_DDD":"44","A1_TEL":"84473652","A1_PFISICA":"57.026.469-8","A1_EMAIL":"danilosouzaadvds@gmail.com","A1_ENDCOB":"RUA CASTRO ALVES,1390 APTO 402, BLOCO 04","A1_COD_MUN":"15200","A1_XCODOAB":"215851","A1_XDTINSC":"20160429","A1_DTNASC":"19910702","A1_XATINAT":"N","A1_XFLCLIE":"01000101","A1_XADIINA":"A","A1_XTPOAB":"02","A1_PESSOA":"F","A1_BAIRROC":"ZONA 06","A1_CEPC":"87015440","A1_MUNC":"MARINGA","A1_XPAI2":"ALBERTO","A1_XMAE2":"MARIA","A1_ESTC":"PR","A1_COMPLEM":"APTO 402, BLOCO 04"}]}
//{"Clientes": [{"A1_COD":"072150","A1_LOJA":"01","A1_NOME":"MARCELO FARIA RAMBALDI","A1_NREDUZ":"72150-1","A1_TIPO":"F","A1_XPAI":"JOSE RAMBALDI","A1_XMAE":"HAYDEE FARIA RAMBALDI","A1_CGC":"00986717827","A1_END":"RUA CELSO DE MELLO","A1_BAIRRO":"VL LAVINIA","A1_CONTA":"11210001","A1_NUM":"87","A1_EST":"SP","A1_CEP":"08735410","A1_DDD":"11","A1_TEL":"28193323","A1_PFISICA":"8.381.426","A1_EMAIL":"advocacia.rambaldi@aasp.org.br","A1_ENDCOB":"AVENIDA GOVERNADOR ADHEMAR DE BARROS,18 ","A1_COD_MUN":"30607","A1_XCODOAB":"072150","A1_XDTINSC":"19831207","A1_DTNASC":"19610214","A1_XATINAT":"S","A1_XFLCLIE":"01001701","A1_XADIINA":"A","A1_XTPOAB":"01","A1_PESSOA":"F","A1_BAIRROC":"CENTRO","A1_CEPC":"08710580","A1_MUNC":"MOGI DAS CRUZES","A1_XPAI2":"JOSE","A1_XMAE2":"HAYDEE","A1_ESTC":"SP","A1_COMPLEM":""}]}
{"Clientes": [{"A1_COD":"039542","A1_LOJA":"13","A1_NOME":"LETICIA GERARD TAVARES MALAGA SOCIEDADE INDIVIDUAL DE ADVOCACIA","A1_NREDUZ":"039542-13","A1_TIPO":"F","A1_XPAI":"","A1_XMAE":"","A1_CGC":"42797473000101","A1_END":"RUA PEDROSO ALVARENGA EDIFICIO DENVER","A1_BAIRRO":"ITAIM BIBI","A1_CONTA":"31120003","A1_NUM":"1284","A1_EST":"SP","A1_CEP":"04531913","A1_DDD":"0","A1_TEL":"0","A1_PFISICA":"","A1_EMAIL":"leticiatmalaga@gmail.com","A1_ENDCOB":"RUA PEDROSO ALVARENGA EDIFICIO DENVER,1284 CONJUNTO 71","A1_COD_MUN":"50308","A1_XCODOAB":"039542","A1_XDTINSC":"20210720","A1_DTNASC":"","A1_XATINAT":"S","A1_XFLCLIE":"01000101","A1_XADIINA":"A","A1_XTPOAB":"13","A1_PESSOA":"J","A1_BAIRROC":"ITAIM BIBI","A1_CEPC":"04531913","A1_MUNC":"SAO PAULO","A1_XPAI2":"","A1_XMAE2":"","A1_ESTC":"SP","A1_COMPLEM":"CONJUNTO 71"}]}